import aidaptive_tool from "../assets/img/aidaptive_tool.jpg";
import stockimg_ai from "../assets/img/stockimg_ai.jpg";
import humata_ai from "../assets/img/humata_ai.jpg";
import sidekick_ai from "../assets/img/sidekick_ai.jpg";
import teal_resume_cuilder_ai from "../assets/img/teal_resume_cuilder_ai.jpg";
import durable_ai from "../assets/img/durable_ai.jpg";
import superflows_ai from "../assets/img/superflows_ai.jpg";
import chatsimple_ai from "../assets/img/chatsimple_ai.jpg";
import gamma_ai from "../assets/img/gamma_ai.jpg";
import monica_ai from "../assets/img/monica_ai.jpg";
import cody_ai from "../assets/img/cody_ai.jpg";
import taplio_ai from "../assets/img/taplio_ai.jpg";
import sellesta_ai from "../assets/img/sellesta_ai.jpg";
import castmagic_ai from "../assets/img/castmagic_ai.jpg";
import creative_reality_studio_ai from "../assets/img/creative_reality_studio_ai.jpg";
import wonderchat_ai from "../assets/img/wonderchat_ai.jpg";
import nexus_ai from "../assets/img/nexus_ai.jpg";
import reimagine_home_ai from "../assets/img/reimagine_home_ai.jpg";
import looka_ai from "../assets/img/looka_ai.jpg";
import predict_ai from "../assets/img/predict_ai.jpg";
import shuffll_ai from "../assets/img/shuffll_ai.jpg";
import lumiere3d_ai from "../assets/img/lumiere3d_ai.jpg";
import storyd_ai from "../assets/img/storyd_ai.jpg";
import journey_ai from "../assets/img/journey_ai.jpg";
import embedditor_ai from "../assets/img/embedditor_ai.jpg";
import assembly_ai from "../assets/img/assembly_ai.jpg";
import loopin_ai from "../assets/img/loopin_ai.jpg";
import branbastionlite_ai from "../assets/img/branbastionlite_ai.jpg";
import ingest_ai from "../assets/img/ingest_ai.jpg";
import uptrends_ai from "../assets/img/uptrends_ai.jpg";
import marketingblocks_ai from "../assets/img/marketingblocks_ai.jpg";
import audioread_ai from "../assets/img/audioread_ai.jpg";
import cohsive_ai from "../assets/img/cohsive_ai.jpg";
import fineshare_ai from "../assets/img/fineshare_ai.jpg";
import neural_ai from "../assets/img/neural_ai.jpg";
import contents_ai from "../assets/img/contents_ai.jpg";
import capsa_ai from "../assets/img/capsa_ai.jpg";
import eightify_ai from "../assets/img/eightify_ai.jpg";
import vondy_ai from "../assets/img/vondy_ai.jpg";
import photo_ai from "../assets/img/photo_ai.jpg";
import chatfuel_ai from "../assets/img/chatfuel_ai.jpg";
import keywordsearch_ai from "../assets/img/keywordsearch_ai.jpg";
import andi_ai from "../assets/img/andi_ai.jpg";
import chatbase_ai from "../assets/img/chatbase_ai.jpg";
import jasper_ai from "../assets/img/jasper_ai.jpg";
import gitmind_ai from "../assets/img/gitmind_ai.jpg";
import gptgo_ai from "../assets/img/gptgo_ai.jpg";
import imgcreater_ai from "../assets/img/imgcreater_ai.jpg";
import synthesysstudio_ai from "../assets/img/synthesysstudio_ai.jpg";
import luni_ai from "../assets/img/luni_ai.jpg";
import magical_ai from "../assets/img/magical_ai.jpg";


export const AIToolsData = [
    {
        id: 1,
        aiImage: aidaptive_tool,
        aiName: "Aidaptive",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Predictive personalization engines for eCommerce and Hospitality",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Free trial",
        aiType: ['#e-commerce'],
        aiUrl: "https://aidaptive.com/",
    },
    {
        id: 2,
        aiImage: stockimg_ai,
        aiName: "StockImg AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "AI-powered design service for logos, images, posters, book covers, and",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Free trial",
        aiType: ['#image generator'],
        aiUrl: "https://stockimg.ai/",
    },
    {
        id: 3,
        aiImage: humata_ai,
        aiName: "Humata AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "ChatGPT for your files. It can summarize long documents into a shorter format.",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiType: ['#research', '#customersupport', '#legal assistane', '#education assistant'],
        aiUrl: "https://www.humata.ai/",
    },
    {
        id: 4,
        aiImage: sidekick_ai,
        aiName: "Sidekick",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Get answers from your apps using natural language.",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiType: ['#startup tools',  '#productivity'],
        aiUrl: "https://www.jigso.io/",
    },
    {
        id: 5,
        aiImage: teal_resume_cuilder_ai,
        aiName: "Teal Resume Builder",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Resume Builder with built-in templates and guidance",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiType: ['#human resources'],
        aiHourlyPrice: "$ 9/wk",
        aiUrl: "https://www.tealhq.com/",
    },
    {
        id: 6,
        aiImage: durable_ai,
        aiName: "Durable",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Create a website, automate marketing & manage finances in 30....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 15/mo",
        aiType: ['#finance', '#low-code/no-code', '#startup tools'],
        aiUrl: "https://durable.co/",
    },
    {
        id: 7,
        aiImage: superflows_ai,
        aiName: "Superflows",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Open Source toolkit for building an AI assistant that lets users control....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 100/mo",
        aiType: ['#low-code/no-code'],
        aiUrl: "https://www.superflows.ai/",
    },
    {
        id: 8,
        aiImage: chatsimple_ai,
        aiName: "Chatsimple",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Custom ChatGPT chatbot trained on your business made simple.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 19/mo",
        aiType: ['#customer support', '#startup tools'],
        aiUrl: "https://www.chatsimple.ai/",
    },
    {
        id: 9,
        aiImage: gamma_ai,
        aiName: "Gamma",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Write Beautiful, engaging content with none of the formatting and....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 19/mo",
        aiType: ['#presentations',  '#copywriting'],
        aiUrl: "https://gamma.app/",
    },
    {
        id: 10,
        aiImage: monica_ai,
        aiName: "Monica",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Personal Al assistant for effortless chatting and copywriting.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 6/mo",
        aiType: ['#general writing', '#productivity'],
        aiUrl: "https://monica.im/",
    },
    {
        id: 11,
        aiImage: cody_ai,
        aiName: "Cody",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "The magic of ChatGPT but trained on your business.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 6/mo",
        aiType: ["#human resources"],
        aiUrl: "https://meetcody.ai/",
    },
    {
        id: 12,
        aiImage: taplio_ai,
        aiName: "Taplio",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Build a personal brand and attract opportunities on LinkedIn.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 39/mo",
        aiType: ['#social media assistant'],
        aiUrl: "https://taplio.com/",
    },
    {
        id: 13,
        aiImage: sellesta_ai,
        aiName: "Sellesta",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Revamp your Amazon business with Sellesta AI tools! Keyword Research....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 14/mo",
        aiType: ['#e-commerce', '#sales'],
        aiUrl: "https://sellesta.com/",
    },
    {
        id: 14,
        aiImage: castmagic_ai,
        aiName: "Castmagic",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI Content Platform For Podcasts, Meetings, and More",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 39/mo",
        aiType: ['#audio editing', '#summarizer', '#transcriber'],
        aiUrl: "https://www.castmagic.io/",
    },
    {
        id: 15,
        aiImage: creative_reality_studio_ai,
        aiName: "Creative Reality Studio (D-ID)",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI-powered platform to create talking avatars from your vision in....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 5.99/mo",
        aiType: ['#video generator'],
        aiUrl: "https://studio.d-id.com/",
    },
    {
        id: 16,
        aiImage: wonderchat_ai,
        aiName: "Wonderchat.io",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Instantly build AI chatbots from a link to your knowledge base or PDF....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 49/mo",
        aiType: ['#customer support'],
        aiUrl: "https://wonderchat.io/",
    },
    {
        id: 17,
        aiImage: nexus_ai,
        aiName: "Nexus - Clay",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "The first AI navigator for your entire network",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#productivity'],
        aiUrl: "https://clay.earth/",
    },
    {
        id: 18,
        aiImage: reimagine_home_ai,
        aiName: "REimagine Home",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Generative AI to redesign any room in seconds",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#design assistant', '#real estate'],
        aiUrl: "https://www.reimaginehome.ai/",
    },
    {
        id: 19,
        aiImage: looka_ai,
        aiName: "Looka",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Create custom logos with Looka Logo Maker and AI.",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#logo generator'],
        aiUrl: "https://looka.com/",
    },
    {
        id: 20,
        aiImage: predict_ai,
        aiName: "Predict AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Predicts customer responses on creative assets",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#design assistant', '#social media assistant'],
        aiUrl: "https://www.neuronsinc.com/",
    },
    {
        id: 21,
        aiImage: shuffll_ai,
        aiName: "Shuffll",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI-powered video production platform for fast, personalized....",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#video editing', '#video generator', '#personalized videos'],
        aiUrl: "https://shuffll.com/",
    },
    {
        id: 22,
        aiImage: lumiere3d_ai,
        aiName: "Lumiere 3D",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Generate immersive 3D videos for e-commerce and marketing....",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 29/mo",
        aiType: ['#e-commerce', '#video generator'],
        aiUrl: "https://www.lumiere3d.ai/",
    },
    {
        id: 23,
        aiImage: storyd_ai,
        aiName: "STORYD",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "It is an AI-powered platform that helps you write and deliver data presentations.",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 18/mo",
        aiType: ['#story teller', '#presentations'],
        aiUrl: "https://www.storyd.ai/",
    },
    {
        id: 24,
        aiImage: journey_ai,
        aiName: "Journey.io",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Journey.io is a storytelling platform that enables users to create....",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 39/mo",
        aiType: ['#presentations'],
        aiUrl: "https://www.journey.io/",
    },
    {
        id: 25,
        aiImage: embedditor_ai,
        aiName: "Embedditor",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "It is the open-source that helps you get the most out of your vector search.",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 39/mo",
        aiType: ['#developer tools'],
        aiUrl: "https://www.journey.io/",
    },
    {
        id: 26,
        aiImage: assembly_ai,
        aiName: "AssemblyAI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Transcribe and understand audio with AI models: ASR, NLP, Speech....",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 0.25/sec",
        aiType: ['#developer tools', '#transcriber'],
        aiUrl: "https://www.assemblyai.com/",
    },
    {
        id: 27,
        aiImage: loopin_ai,
        aiName: "Loopin AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Turn your meetings into workspaces where your whole team can....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 12/mo",
        aiType: ['#summarizer', '#transcriber', '#productivity'],
        aiUrl: "https://www.loopinhq.com/",
    },
    {
        id: 28,
        aiImage: branbastionlite_ai,
        aiName: "BrandBastion Lite",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Easily monitor and manage all your social media conversations",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 74/mo",
        aiType: ['#customer support', '#social media assistant'],
        aiUrl: "https://www.brandbastion.com/",
    },
    {
        id: 29,
        aiImage: ingest_ai,
        aiName: "IngestAI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "One-stop shop for anyone looking to leverage AI.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#productivity'],
        aiUrl: "https://www.brandbastion.com/",
    },
    {
        id: 30,
        aiImage: uptrends_ai,
        aiName: "IngestAI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Analyzing stock market chatter to help you find trends & events that....",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 14/mo",
        aiType: ['#finance'],
        aiUrl: "https://www.brandbastion.com/",
    },
    {
        id: 31,
        aiImage: marketingblocks_ai,
        aiName: "MarketingBlocks AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "All Your Marketing Assets In ANY niche and ANY language from just a keyword.",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 57/mo",
        aiType: ['#design assistant','#copywriting'],
        aiUrl: "https://marketingblocks.ai/",
    },
    {
        id: 32,
        aiImage: audioread_ai,
        aiName: "Audioread.com",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Listen to articles, PDFs, emails, YouTube in your podcast player",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 9/mo",
        aiType: ['#productivity'],
        aiUrl: "https://audioread.com/",
    },
    {
        id: 33,
        aiImage: cohsive_ai,
        aiName: "Cohesive",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "The most powerful AI editor that amplifies your creativity and....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 9/mo",
        aiType: ['#copywriting'],
        aiUrl: "https://cohesive.so/",
    },
    {
        id: 34,
        aiImage: fineshare_ai,
        aiName: "FineShare FineCam",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Transform your video calls and recordings with FineShare FineCam....",
        aiPriceType: "fa fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 9/mo",
        aiType: ['#video editing'],
        aiUrl: "https://www.fineshare.com/",
    },
    {
        id: 35,
        aiImage: neural_ai,
        aiName: "Neural Newsletters",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI-powered platform for creating engaging newsletters with curated....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 97/mo",
        aiType: ['#general writing'],
        aiUrl: "https://neuralnewsletters.com/",
    },
    {
        id: 36,
        aiImage: contents_ai,
        aiName: "Contents",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Contents is the Generative AI platform to create impactful....",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#copywriting'],
        aiUrl: "https://www.contents.com/",
    },
    {
        id: 37,
        aiImage: capsa_ai,
        aiName: "Caspa AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Create & edit AI images for your brand in minutes.",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#image generator'],
        aiUrl: "https://www.caspa.ai/",
    },
    {
        id: 38,
        aiImage: eightify_ai,
        aiName: "Eightify",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Summaries for YT: 8 key ideas to decide if video is worth watching.",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#summarizer'],
        aiUrl: "https://eightify.app/",
    },
    {
        id: 39,
        aiImage: vondy_ai,
        aiName: "Vondy AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "It is an  Ai software that help in creativity assistant",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#productivity'],
        aiUrl: "https://www.vondy.com/",
    },
    {
        id: 40,
        aiImage: photo_ai,
        aiName: "Photo AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "It is an  Ai software that help in creativity photographer",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 29/mo",
        aiType: ['#image editing', '#avatars'],
        aiUrl: "https://photoai.com/",
    },
    {
        id: 41,
        aiImage: chatfuel_ai,
        aiName: "Chatfuel AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI-powered chatbot platform: elevate customer support and sales",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 29/mo",
        aiType: ['#customer support'],
        aiUrl: "https://chatfuel.com/",
    },
    {
        id: 42,
        aiImage: keywordsearch_ai,
        aiName: "KeywordSearch",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "KeywordSearch AI boosts ROI for Google & YouTube Ads. Find Best A....",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 97/mo",
        aiType: ['#social media assistant'],
        aiUrl: "https://www.keywordsearch.com/",
    },
    {
        id: 43,
        aiImage: keywordsearch_ai,
        aiName: "MagicForm",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Train AI salesperson to boost conversions 20% in 3 mins",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 99/mo",
        aiType: ['#low-code/no-code','#sales'],
        aiUrl: "https://www.magicform.ai/",
    },
    {
        id: 44,
        aiImage: andi_ai,
        aiName: "Andi",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Andi is a generative AI-powered search engine that provides direct....",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 99/mo",
        aiType: ['#search engine'],
        aiUrl: "https://andisearch.com/",
    },
    {
        id: 45,
        aiImage: chatbase_ai,
        aiName: "Chatbase",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Build an AI chatbot trained on your data",
        aiPriceType: "fa fa-dollar-sign",
        aiPrice: "paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 19/mo",
        aiType: ['#education assistant'],
        aiUrl: "https://www.chatbase.co/",
    },
    {
        id: 46,
        aiImage: jasper_ai,
        aiName: "Jasper",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Create content 10x faster with AI-powered copywriting tool",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 40/mo",
        aiType: ['#copywriting'],
        aiUrl: "https://www.jasper.ai/",
    },
    {
        id: 47,
        aiImage: gitmind_ai,
        aiName: "GitMind AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Boost Your Mind Mapping Speed with GitMind's AI-Powered Tool",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 9/mo",
        aiType: ['#productivity'],
        aiUrl: "https://gitmind.com/",
    },
    {
        id: 48,
        aiImage: gptgo_ai,
        aiName: "GPTGO",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "ChatGPT combined with Google search",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 9/mo",
        aiType: ['#life assistant','#search engine'],
        aiUrl: "https://gptgo.ai/",
    },
    {
        id: 49,
        aiImage: imgcreater_ai,
        aiName: "Imgcreator",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Best AI Anime Generator and Photo Background Generator.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 9/mo",
        aiType: ['#e-commerce'],
        aiUrl: "https://imgcreator.zmo.ai/",
    },
    {
        id: 50,
        aiImage: synthesysstudio_ai,
        aiName: "Synthesys Studio",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Synthesys develops algorithms for text-to-voiceover and videos for....",
        aiPriceType: "fa fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 27/mo",
        aiType: ['#text to speech','#video generator'],
        aiUrl: "https://synthesys.io/",
    },
    {
        id: 51,
        aiImage: luni_ai,
        aiName: "Luna Ai",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Create better Linkedin content 10x Faster with Ai",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 27/mo",
        aiType: ['#social media assistant'],
        aiUrl: "https://www.lunaa.io/",
    },
    {
        id: 52,
        aiImage: magical_ai,
        aiName: "Magical",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Magical AI - Welcome to the future of calendaring.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 15/mo",
        aiType: ['#summarizer','#productivity'],
        aiUrl: "https://magical.so/",
    },
]