import aidaptive_tool from "../assets/img/aidaptive_tool.jpg";
import stockimg_ai from "../assets/img/stockimg_ai.jpg";
import humata_ai from "../assets/img/humata_ai.jpg";
import sidekick_ai from "../assets/img/sidekick_ai.jpg";
import teal_resume_cuilder_ai from "../assets/img/teal_resume_cuilder_ai.jpg";
import durable_ai from "../assets/img/durable_ai.jpg";
import superflows_ai from "../assets/img/superflows_ai.jpg";
import chatsimple_ai from "../assets/img/chatsimple_ai.jpg";
import gamma_ai from "../assets/img/gamma_ai.jpg";
import monica_ai from "../assets/img/monica_ai.jpg";
import cody_ai from "../assets/img/cody_ai.jpg";
import taplio_ai from "../assets/img/taplio_ai.jpg";
import sellesta_ai from "../assets/img/sellesta_ai.jpg";
import castmagic_ai from "../assets/img/castmagic_ai.jpg";
import creative_reality_studio_ai from "../assets/img/creative_reality_studio_ai.jpg";
import wonderchat_ai from "../assets/img/wonderchat_ai.jpg";
import nexus_ai from "../assets/img/nexus_ai.jpg";
import reimagine_home_ai from "../assets/img/reimagine_home_ai.jpg";
import looka_ai from "../assets/img/looka_ai.jpg";
import predict_ai from "../assets/img/predict_ai.jpg";
import shuffll_ai from "../assets/img/shuffll_ai.jpg";


export const AIToolsData = [
    {
        id: 1,
        aiImage: aidaptive_tool,
        aiName: "Aidaptive",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Predictive personalization engines for eCommerce and Hospitality",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Free trial",
        aiType: ['#e-commerce'],
        aiUrl: "https://aidaptive.com/",
    },
    {
        id: 2,
        aiImage: stockimg_ai,
        aiName: "StockImg AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "AI-powered design service for logos, images, posters, book covers, and",
        aiPriceType: "fas fa-unlock-alt",
        aiPrice: "Free trial",
        aiType: ['#image generator'],
        aiUrl: "https://stockimg.ai/",
    },
    {
        id: 3,
        aiImage: humata_ai,
        aiName: "Humata AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "ChatGPT for your files. It can summarize long documents into a shorter format.",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiType: ['#research', '#customersupport', '#legal assistane', '#education assistant'],
        aiUrl: "https://www.humata.ai/",
    },
    {
        id: 4,
        aiImage: sidekick_ai,
        aiName: "Sidekick",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Get answers from your apps using natural language.",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiType: ['#startup tools',  '#productivity'],
        aiUrl: "https://www.jigso.io/",
    },
    {
        id: 5,
        aiImage: teal_resume_cuilder_ai,
        aiName: "Teal Resume Builder",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Resume Builder with built-in templates and guidance",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiType: ['#human resources'],
        aiHourlyPrice: "$ 9/wk",
        aiUrl: "https://www.tealhq.com/",
    },
    {
        id: 6,
        aiImage: durable_ai,
        aiName: "Durable",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Create a website, automate marketing & manage finances in 30....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 15/mo",
        aiType: ['#finance', '#low-code/no-code', '#startup tools'],
        aiUrl: "https://durable.co/",
    },
    {
        id: 7,
        aiImage: superflows_ai,
        aiName: "Superflows",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Open Source toolkit for building an AI assistant that lets users control....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 100/mo",
        aiType: ['#low-code/no-code'],
        aiUrl: "https://www.superflows.ai/",
    },
    {
        id: 8,
        aiImage: chatsimple_ai,
        aiName: "Chatsimple",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Custom ChatGPT chatbot trained on your business made simple.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 19/mo",
        aiType: ['#customer support', '#startup tools'],
        aiUrl: "https://www.chatsimple.ai/",
    },
    {
        id: 9,
        aiImage: gamma_ai,
        aiName: "Gamma",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Write Beautiful, engaging content with none of the formatting and....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 19/mo",
        aiType: ['#presentations',  '#copywriting'],
        aiUrl: "https://gamma.app/",
    },
    {
        id: 10,
        aiImage: monica_ai,
        aiName: "Monica",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Personal Al assistant for effortless chatting and copywriting.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 6/mo",
        aiType: ['#general writing', '#productivity'],
        aiUrl: "https://monica.im/",
    },
    {
        id: 11,
        aiImage: cody_ai,
        aiName: "Cody",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "The magic of ChatGPT but trained on your business.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 6/mo",
        aiType: ["#human resources"],
        aiUrl: "https://meetcody.ai/",
    },
    {
        id: 12,
        aiImage: taplio_ai,
        aiName: "Taplio",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Build a personal brand and attract opportunities on LinkedIn.",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 39/mo",
        aiType: ['#social media assistant'],
        aiUrl: "https://taplio.com/",
    },
    {
        id: 13,
        aiImage: sellesta_ai,
        aiName: "Sellesta",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Revamp your Amazon business with Sellesta AI tools! Keyword Research....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 14/mo",
        aiType: ['#e-commerce', '#sales'],
        aiUrl: "https://sellesta.com/",
    },
    {
        id: 14,
        aiImage: castmagic_ai,
        aiName: "Castmagic",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI Content Platform For Podcasts, Meetings, and More",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 39/mo",
        aiType: ['#audio editing', '#summarizer', '#transcriber'],
        aiUrl: "https://www.castmagic.io/",
    },
    {
        id: 15,
        aiImage: creative_reality_studio_ai,
        aiName: "Creative Reality Studio (D-ID)",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI-powered platform to create talking avatars from your vision in....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 5.99/mo",
        aiType: ['#video generator'],
        aiUrl: "https://studio.d-id.com/",
    },
    {
        id: 16,
        aiImage: wonderchat_ai,
        aiName: "Wonderchat.io",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Instantly build AI chatbots from a link to your knowledge base or PDF....",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Free Trial",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 49/mo",
        aiType: ['#customer support'],
        aiUrl: "https://wonderchat.io/",
    },
    {
        id: 17,
        aiImage: nexus_ai,
        aiName: "Nexus - Clay",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "The first AI navigator for your entire network",
        aiPriceType: "fa fa-unlock-alt",
        aiPrice: "Freemium",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#productivity'],
        aiUrl: "https://clay.earth/",
    },
    {
        id: 18,
        aiImage: reimagine_home_ai,
        aiName: "REimagine Home",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star-half"],
        aiDescription: "Generative AI to redesign any room in seconds",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#design assistant', '#real estate'],
        aiUrl: "https://www.reimaginehome.ai/",
    },
    {
        id: 19,
        aiImage: looka_ai,
        aiName: "Looka",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Create custom logos with Looka Logo Maker and AI.",
        aiPriceType: "fa fa-check-circle",
        aiPrice: "Free",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#logo generator'],
        aiUrl: "https://looka.com/",
    },
    {
        id: 20,
        aiImage: predict_ai,
        aiName: "Predict AI",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "Predicts customer responses on creative assets",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#design assistant', '#social media assistant'],
        aiUrl: "https://www.neuronsinc.com/",
    },
    {
        id: 21,
        aiImage: shuffll_ai,
        aiName: "Shuffll",
        aiRating: ["fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star", "fa fa-star"],
        aiDescription: "AI-powered video production platform for fast, personalized....",
        aiPriceType: "fas fa-dollar-sign",
        aiPrice: "Paid",
        aiPriceTag: "fa fa-tag",
        aiPriceTagName: "Deals",
        aiHourlyPrice: "$ 20/mo",
        aiType: ['#video editing', '#video generator', '#personalized videos'],
        aiUrl: "https://shuffll.com/",
    },
]